name: Test installation of plugins
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-plugin-installation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Install Kurtosis
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
